Repository bhsrampage/argoumlFall2024_cloneFork, pull requests merged in 2024-11, with the labels that each got.

#6 Remove code duplicates from UMLEditableComboBox.java
  .idea/misc.xml
  src/argouml-core-umlpropertypanels/src/org/argouml/core/propertypanels/ui/UMLEditableComboBox.java
Labels: Remove Software Clone

#20 OWASP Uncontrolled Resource Consumption Vulnerability in commons-io-2.11.0.jar #65, XML External Entity (XXE) Vulnerability in UmlFilePersister Class #64
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  .idea/workspace.xml
  src/argouml-app/pom.xml
  src/argouml-app/src/org/argouml/persistence/UmlFilePersister.java
  src/argouml-core-model-mdr/src/org/argouml/model/mdr/XmiReferenceResolverImpl.java
Labels: Group 19

#21 [SpotBug] fix: overridable method call inside constructor
  src/argouml-app/src/org/argouml/cognitive/Critic.java
Labels: Group 19, Remove Software Vulnerability
